#!/bin/bash                                                                     

cd server/
echo starting main server.
gnome-terminal -- erl -noshell -name main_server@192.168.1.103 -config config/main -setcookie secure123 -s chat_server
cd ..
