#!/bin/bash                                                                     

cd server/
echo Starting main server.
gnome-terminal -- erl -noshell -name main_server@192.168.1.103 -config config/main -setcookie secure123 -s chat_server
echo Starting backup server.
gnome-terminal -- erl -noshell -name backup_server@192.168.1.103 -config config/backup -setcookie secure123 -s chat_server
cd ..
