#!/bin/bash                                                                     
echo Starting backup server.
gnome-terminal -- erl -noshell -name backup_server@192.168.1.103 -pa server -config server/config/backup -setcookie secure123 -s chat_server

