#!/bin/bash                                                                     
echo Starting main server.
gnome-terminal -- erl -noshell -name main_server@192.168.1.103 -pa server -config server/config/main -setcookie secure123 -s chat_server