#!/bin/bash                                                                     

./compile
erl -eval 'xref:start(s), xref:add_directory(s, "./client"), xref:add_directory(s, "./server")'

# xref:analyze(s, undefined_function_calls).
# xref:analyze(s, undefined_function_calls).
# xref:analyze(s, undefined_functions).
# xref:analyze(s, locals_not_used).
# xref:analyze(s, exports_not_used).
# xref:analyze(s, deprecated_function_calls).
# xref:analyze(s, deprecated_functions).